FROM golang:1.22.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o todo-app .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/todo-app .

EXPOSE 8080

CMD ["./todo-app"]